#!/bin/bash

# onedrive for linux: https://github.com/abraunegg/onedrive

set -a
source ~/.telegram_env
set +a

LOGFILE="/home/m1tus/.log/onedrive-sync.log"
LOGDIR=$(dirname $LOGFILE)

ONEDRIVE_ARGS="--sync"
if [ $# -gt 0 ]; then
    ONEDRIVE_ARGS="$@"
fi

function exec_sync() {
    local TIMESTAMP=$(date '+%d-%m-%Y %H:%M:%S')

    echo "$TIMESTAMP $(hostname)" >> "$LOGFILE"
    if [ -t 1 ]; then
        onedrive "$ONEDRIVE_ARGS"
    else
        onedrive "$ONEDRIVE_ARGS" 2>&1 >/dev/null
    fi
}

function notify_user() {
    local message="$1"
    local body="$2"

    local user="m1tus"
    local uid=$(id -u $user)
    local dbus_address="unix:path=/run/user/$uid/bus"

    sudo -u $user DISPLAY=:0 DBUS_SESSION_BUS_ADDRESS=$dbus_address notify-send "$message" "$body"
}

# ------------------------------------------------------------------------- #

if [ ! -d "$LOGDIR" ]; then
    echo "Directory $LOGDIR does not exist"
    notify_user "OneDrive Update Failed" "Directory $LOGDIR does not exist"
    exit 1
fi

touch "$LOGFILE"

if [ $? -ne 0 ]; then
    echo "Log file could not be created. Check permissions"
    notify_user "OneDrive Update Failed" "Log file could not be created"
    exit 1
fi

exec_sync

if [ $? -ne 0 ]; then
    notify_user "OneDrive Update Failed" "KO"
    MESSAGE="[KO] OneDrive sync failed $(hostname) at: $(date)"
    curl -s -X POST "https://api.telegram.org/bot$BOT_TOKEN/sendMessage" \
         -d chat_id="$CHAT_ID" \
         -d text="$MESSAGE"
    exit 1
fi

exit 0
