#!/bin/bash

GREEN='\033[0;32m'
DEFAULT='\033[0m'

sudo -v

if [ $? -eq 0 ]; then
    echo -e "${GREEN}--- Updating apt packages ---${DEFAULT}"
        sudo apt update && sudo apt full-upgrade -y
    echo -e "${GREEN}--- done ---${DEFAULT}"
    echo -e "${GREEN}--- Removing unused dependencies ---${DEFAULT}"
        sudo apt autoremove -y
    echo -e "${GREEN}--- done ---${DEFAULT}"
else
    echo -e "${GREEN}Auth failed${DEFAULT}"
fi
